services:
    _defaults:
        autowire: true
        public: true

    chaplean_rest_client.listener.request_executed:
        class: Chaplean\Bundle\RestClientBundle\EventListener\RequestExecutedListener
        arguments:
          - '@chaplean_rest_client.utility.rest_log'
          - '@chaplean_rest_client.utility.email'
        tags:
          - { name: kernel.event_subscriber, connection: default }

    chaplean_rest_client.query.rest_log:
        class: Chaplean\Bundle\RestClientBundle\Query\RestLogQuery
        arguments:
          - '@?doctrine'

    chaplean_rest_client.utility.rest_log:
        class: Chaplean\Bundle\RestClientBundle\Utility\RestLogUtility
        arguments:
          - '%chaplean_rest_client.config%'
          - '@chaplean_rest_client.query.rest_log'
          - '@?doctrine'

    chaplean_rest_client.utility.email:
        class: Chaplean\Bundle\RestClientBundle\Utility\EmailUtility
        arguments:
          - '%chaplean_rest_client.config%'
          - '@?mailer'
          - '@?translator'
          - '@?templating.engine.twig'
